apiVersion: operator.aws/v1alpha1
kind: S3Bucket
metadata:
  name: s3bucket.aws-operator.com
spec:
  versioning: true
  accessControl: PublicRead
  website:
    enabled: true
    indexPage: index.html
    errorPage: 500.html
  logging:
    enabled: false
    prefix: "archive"
