apiVersion: operator.aws/v1alpha1
kind: SQSQueue
metadata:
  name: chrishein-test-sqs-2
spec:
  contentBasedDeduplication: true
  delaySeconds: 5
  usedeadletterQueue: false
  maximumMessageSize: 262144
  messageRetentionPeriod: 345600
  visibilityTimeout: 30


