apiVersion: v1
kind: List
items:
- kind: Namespace
  apiVersion: v1
  metadata:
    name: aws-operator

- kind: ClusterRole
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: aws-operator
    namespace: aws-operator
  rules:
  - apiGroups:
    - v1
    resources:
    - secrets
    - pods
    - configmaps
    - services
    verbs:
    - get
    - list
    - watch
    - create
    - delete
    - update
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - get
    - list
    - watch
    - create
    - delete
  - apiGroups:
    - operator.aws
    resources:
    - "*"
    verbs:
    - "*"

- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: aws-operator
    namespace: aws-operator

- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: aws-operator
    namespace: aws-operator
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: aws-operator
  subjects:
  - kind: ServiceAccount
    name: aws-operator
    namespace: default

- kind: Deployment
  apiVersion: apps/v1beta1
  metadata:
    name: aws-operator
    namespace: aws-operator
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: aws-operator
      spec:
        serviceAccountName: aws-operator
        containers:
        - name: aws-operator
          image: <account-id>.dkr.ecr.us-west-2.amazonaws.com/aws-operator:v0.0.1.alpha1
          imagePullPolicy: Always
          env:
            - name: AWS_ACCESS_KEY_ID
              value:
            - name: AWS_SECRET_ACCESS_KEY
              value:
          args:
            - --cluster-name=<cluster-name>
            - --region=<region>
            - --bucket=<bucket-name>
            - --account-id=<account-id>
