---
kind: Namespace
apiVersion: v1
metadata:
  name: aws-operator
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: aws-operator
  namespace: aws-operator
rules:
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - operator.aws
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-operator
  namespace: aws-operator
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: aws-operator
  namespace: aws-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-operator
subjects:
- kind: ServiceAccount
  name: aws-operator
  namespace: default
# TODO: Uncomment when you have an image to deploy
# ---
# apiVersion: apps/v1beta1
# kind: Deployment
# metadata:
#   name: aws-operator
#   namespace: aws-operator
# spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: aws-operator
#     spec:
#       serviceAccountName: aws-operator
#       containers:
#       - name: aws-operator
#         image: christopherhein/aws-operator:VERSION_NUMBER
#         imagePullPolicy: Always
